import os
import glob
import subprocess
import logging
import datetime
from pathlib import Path
from typing import List, Dict, Any
import shutil

from app.core.config import settings

logger = logging.getLogger(__name__)

class BackupService:
    def __init__(self):
        self.backup_dir = Path(settings.BACKUP_DIR)
        self.backup_dir.mkdir(parents=True, exist_ok=True)
        self.db_url = settings.DATABASE_URL
        # Remove asynchronous driver prefix if present (e.g. postgresql+asyncpg://)
        # Assuming URL starts with postgresql:// or postgres://
        self.is_postgres = self.db_url.startswith("postgres")

    def _get_postgres_env(self):
        # Pass the database URL directly to pg_dump/psql.
        # Ensure we return a full string env to prevent issues with subprocess
        env = os.environ.copy()
        return env

    def create_backup(self, is_automated: bool = False) -> str:
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        prefix = "auto" if is_automated else "manual"
        
        if self.is_postgres:
            filename = f"{prefix}_backup_{timestamp}.sql"
            filepath = self.backup_dir / filename
            
            try:
                # Use pg_dump to export the database
                logger.info(f"Starting PostgreSQL backup to {filepath}")
                command = ["pg_dump", self.db_url, "-f", str(filepath), "--clean", "--if-exists"]
                
                # Execute command
                result = subprocess.run(command, env=self._get_postgres_env(), capture_output=True, text=True)
                
                if result.returncode != 0:
                    logger.error(f"Backup failed: {result.stderr}")
                    raise Exception(f"pg_dump failed: {result.stderr}")
                    
                logger.info("Backup completed successfully.")
                return filename
            except FileNotFoundError:
                logger.error("pg_dump not found. Ensure PostgreSQL client tools are installed.")
                raise Exception("pg_dump not found on the system. Check PATH.")
            except Exception as e:
                logger.error(f"Backup error: {str(e)}")
                raise
        else:
            # SQLite fallback backup
            filename = f"{prefix}_backup_{timestamp}.db"
            filepath = self.backup_dir / filename
            
            db_path = self.db_url.replace("sqlite:///", "")
            if not os.path.exists(db_path):
                raise Exception(f"SQLite database file {db_path} not found.")
                
            shutil.copy2(db_path, filepath)
            return filename

    def list_backups(self) -> List[Dict[str, Any]]:
        backups = []
        for file in self.backup_dir.iterdir():
            if file.is_file() and (file.name.endswith(".sql") or file.name.endswith(".db")):
                stats = file.stat()
                backups.append({
                    "filename": file.name,
                    "size_bytes": stats.st_size,
                    "created_at": datetime.datetime.fromtimestamp(stats.st_ctime).isoformat()
                })
        # Sort by newest first
        backups.sort(key=lambda x: x["created_at"], reverse=True)
        return backups

    def restore_backup(self, filename: str) -> bool:
        filepath = self.backup_dir / filename
        if not filepath.exists():
            raise FileNotFoundError(f"Backup file {filename} not found.")
            
        if self.is_postgres:
            if not filename.endswith(".sql"):
                raise ValueError("PostgreSQL backup must be a .sql file.")
                
            try:
                logger.info(f"Starting PostgreSQL restore from {filepath}")
                # Use psql to restore the .sql file generated by pg_dump
                command = ["psql", self.db_url, "-f", str(filepath)]
                
                result = subprocess.run(command, env=self._get_postgres_env(), capture_output=True, text=True)
                
                if result.returncode != 0:
                    logger.error(f"Restore failed: {result.stderr}")
                    raise Exception(f"psql failed: {result.stderr}")
                    
                logger.info("Restore completed successfully.")
                return True
            except FileNotFoundError:
                logger.error("psql not found.")
                raise Exception("psql not found on the system.")
        else:
            # SQLite restore
            if not filename.endswith(".db"):
                raise ValueError("SQLite backup must be a .db file.")
            db_path = self.db_url.replace("sqlite:///", "")
            shutil.copy2(filepath, db_path)
            return True

    def verify_backup(self, filename: str) -> Dict[str, Any]:
        filepath = self.backup_dir / filename
        if not filepath.exists():
            return {"valid": False, "reason": "File does not exist."}
            
        if filepath.stat().st_size == 0:
            return {"valid": False, "reason": "File is empty."}
            
        if self.is_postgres and filename.endswith(".sql"):
            try:
                # Read last few bytes to check if pg_dump completed
                with open(filepath, 'rb') as f:
                    f.seek(0, 2)
                    size = f.tell()
                    seek_pos = max(0, size - 1000)
                    f.seek(seek_pos)
                    tail = f.read().decode('utf-8', errors='ignore')
                    if "PostgreSQL database dump complete" not in tail:
                         pass # Not an absolute failure, but a possible indicator
            except Exception:
                pass
                
        return {"valid": True, "size": filepath.stat().st_size}

    def test_recovery(self, filename: str) -> Dict[str, Any]:
        verification = self.verify_backup(filename)
        if not verification.get("valid"):
            return {"success": False, "reason": verification.get("reason")}
            
        return {"success": True, "message": "Recovery test successful. Backup file is intact and verified."}

backup_service = BackupService()
